import { DataSource } from '../../types';

export interface MetricDefinition {
  id: string;
  domain: "biometrics" | "sleep" | "training" | "nutrition" | "mental" | "recovery" | "context";
  label: string;
  description: string;
  unit: string;
  allowedUnits: string[];
  sourceTypes: DataSource[];
  valueType: "number" | "boolean" | "categorical" | "text";
  normalRange?: {
    min?: number;
    max?: number;
    note?: string;
  };
  validRange?: {
    min?: number;
  };
  aggregation: "sum" | "mean" | "min" | "max" | "latest" | "weighted";
  higherIsBetter?: boolean;
  confidenceRules: string[];
  scientificStatus: "robust" | "probable" | "exploratory" | "weak_signal";
  medicalRisk: "none" | "wellness_only" | "requires_context" | "medical_boundary";
}

export const metricRegistry: Record<string, MetricDefinition> = {
  // === Garmin - Biometrics ===
  hrv_rmssd: {
    id: "hrv_rmssd",
    domain: "biometrics",
    label: "HRV (RMSSD)",
    description: "Variabilité de la fréquence cardiaque (Root Mean Square of Successive Differences). Reflet direct du tonus parasympathique et de la récupération.",
    unit: "ms",
    allowedUnits: ["ms"],
    sourceTypes: ["garmin", "derived"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: true,
    confidenceRules: ["Baisse de confiance de 20% si l'ECG/capteur a des artefacts", "Invalide si durée < 2 min"],
    scientificStatus: "robust",
    medicalRisk: "wellness_only"
  },
  rhr: {
    id: "rhr",
    domain: "biometrics",
    label: "Rythme Cardiaque au Repos (RHR)",
    description: "Fréquence cardiaque minimale mesurée pendant le sommeil ou au réveil complet.",
    unit: "bpm",
    allowedUnits: ["bpm"],
    sourceTypes: ["garmin", "manual"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: false,
    confidenceRules: ["Confiance élevée si mesuré durant un sommeil stable"],
    scientificStatus: "robust",
    medicalRisk: "wellness_only"
  },
  resting_hr: {
    id: "resting_hr",
    domain: "biometrics",
    label: "Fréquence Cardiaque de Repos Éveillé",
    description: "Fréquence cardiaque au repos durant la journée hors activité physique.",
    unit: "bpm",
    allowedUnits: ["bpm"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: false,
    confidenceRules: ["Peut être influencé par le stress aigu de la journée"],
    scientificStatus: "probable",
    medicalRisk: "wellness_only"
  },
  avg_hr: {
    id: "avg_hr",
    domain: "biometrics",
    label: "Fréquence Cardiaque Moyenne",
    description: "Fréquence cardiaque moyenne mesurée sur 24 heures.",
    unit: "bpm",
    allowedUnits: ["bpm"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: false,
    confidenceRules: [],
    scientificStatus: "robust",
    medicalRisk: "none"
  },
  max_hr: {
    id: "max_hr",
    domain: "biometrics",
    label: "Fréquence Cardiaque Maximale",
    description: "Fréquence cardiaque maximale enregistrée (généralement pendant l'effort).",
    unit: "bpm",
    allowedUnits: ["bpm"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "max",
    higherIsBetter: false,
    confidenceRules: ["Peut être causé par un pic d'artefact optique"],
    scientificStatus: "robust",
    medicalRisk: "requires_context"
  },
  respiration_rate: {
    id: "respiration_rate",
    domain: "biometrics",
    label: "Fréquence Respiratoire",
    description: "Nombre de respirations par minute moyen sur 24h ou durant le sommeil.",
    unit: "brpm",
    allowedUnits: ["brpm"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: false,
    confidenceRules: ["Basé sur l'analyse HRV, moins fiable en cas d'arythmie"],
    scientificStatus: "probable",
    medicalRisk: "requires_context"
  },
  spo2: {
    id: "spo2",
    domain: "biometrics",
    label: "Saturation en Oxygène (SpO2)",
    description: "Taux d'oxygène dans le sang mesuré par oxymétrie de pouls.",
    unit: "%",
    allowedUnits: ["%"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: true,
    confidenceRules: ["Les capteurs au poignet génèrent de fréquents faux négatifs lors de mouvements"],
    scientificStatus: "probable",
    medicalRisk: "medical_boundary"
  },
  body_battery: {
    id: "body_battery",
    domain: "biometrics",
    label: "Body Battery",
    description: "Estimation Garmin de l'énergie corporelle restante basée sur HRV, sommeil et stress.",
    unit: "%",
    allowedUnits: ["%"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "latest",
    higherIsBetter: true,
    confidenceRules: ["Baisse de confiance si la montre n'est pas portée de manière continue"],
    scientificStatus: "exploratory",
    medicalRisk: "none"
  },
  stress_score: {
    id: "stress_score",
    domain: "biometrics",
    label: "Score de Stress Garmin",
    description: "Niveau de stress physiologique global calculé par l'analyse HRV en continu.",
    unit: "/100",
    allowedUnits: ["/100"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: false,
    confidenceRules: ["Non mesuré en présence d'activité physique intense"],
    scientificStatus: "probable",
    medicalRisk: "wellness_only"
  },
  weight: {
    id: "weight",
    domain: "biometrics",
    label: "Poids Corporel",
    description: "Poids mesuré manuellement ou via balance connectée Garmin.",
    unit: "kg",
    allowedUnits: ["kg", "lbs"],
    sourceTypes: ["garmin", "manual"],
    valueType: "number",
    aggregation: "latest",
    higherIsBetter: true,
    confidenceRules: [],
    scientificStatus: "robust",
    medicalRisk: "none"
  },

  // === Garmin - Sleep ===
  sleep_duration: {
    id: "sleep_duration",
    domain: "sleep",
    label: "Durée du Sommeil",
    description: "Temps total passé endormi (somme des phases).",
    unit: "h",
    allowedUnits: ["h", "min", "s"],
    sourceTypes: ["garmin", "manual"],
    valueType: "number",
    aggregation: "sum",
    higherIsBetter: true,
    confidenceRules: ["Flag et réduction de confiance si le sommeil Garmin a un score mais pas de durée"],
    scientificStatus: "robust",
    medicalRisk: "none"
  },
  sleep_score: {
    id: "sleep_score",
    domain: "sleep",
    label: "Score de Sommeil Garmin",
    description: "Score global de qualité du sommeil (0 à 100) calculé par Garmin.",
    unit: "/100",
    allowedUnits: ["/100"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: true,
    confidenceRules: ["Considéré comme une donnée empirique utile mais non absolue"],
    scientificStatus: "probable",
    medicalRisk: "none"
  },
  sleep_efficiency: {
    id: "sleep_efficiency",
    domain: "sleep",
    label: "Efficacité du Sommeil",
    description: "Ratio du temps endormi sur le temps total passé au lit.",
    unit: "%",
    allowedUnits: ["%"],
    sourceTypes: ["garmin", "derived"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: true,
    confidenceRules: ["Nécessite des heures de coucher/lever précises"],
    scientificStatus: "robust",
    medicalRisk: "none"
  },
  sleep_deep_duration: {
    id: "sleep_deep_duration",
    domain: "sleep",
    label: "Sommeil Profond",
    description: "Durée cumulée en sommeil profond (ondes lentes). Essentiel pour la récupération physique.",
    unit: "h",
    allowedUnits: ["h", "min", "s"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "sum",
    higherIsBetter: true,
    confidenceRules: ["La classification par actigraphie optique comporte environ 30% d'incertitude vs polysomnographie"],
    scientificStatus: "probable",
    medicalRisk: "none"
  },
  sleep_light_duration: {
    id: "sleep_light_duration",
    domain: "sleep",
    label: "Sommeil Léger",
    description: "Durée passée en sommeil léger.",
    unit: "h",
    allowedUnits: ["h", "min", "s"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "sum",
    higherIsBetter: true,
    confidenceRules: [],
    scientificStatus: "probable",
    medicalRisk: "none"
  },
  sleep_rem_duration: {
    id: "sleep_rem_duration",
    domain: "sleep",
    label: "Sommeil REM (Paradoxal)",
    description: "Durée passée en sommeil paradoxal (rêves, consolidation mentale).",
    unit: "h",
    allowedUnits: ["h", "min", "s"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "sum",
    higherIsBetter: true,
    confidenceRules: ["Identification optique du REM parfois confondue avec le sommeil léger / micro-réveils"],
    scientificStatus: "probable",
    medicalRisk: "none"
  },
  sleep_awake_duration: {
    id: "sleep_awake_duration",
    domain: "sleep",
    label: "Temps Éveillé (Sommeil)",
    description: "Temps total mesuré en état d'éveil au milieu de la nuit.",
    unit: "h",
    allowedUnits: ["h", "min", "s"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "sum",
    higherIsBetter: false,
    confidenceRules: [],
    scientificStatus: "robust",
    medicalRisk: "none"
  },
  sleep_start_time: {
    id: "sleep_start_time",
    domain: "sleep",
    label: "Heure de Coucher",
    description: "Heure estimée de l'endormissement.",
    unit: "HH:MM",
    allowedUnits: ["HH:MM"],
    sourceTypes: ["garmin", "manual"],
    valueType: "text",
    aggregation: "latest",
    confidenceRules: [],
    scientificStatus: "robust",
    medicalRisk: "none"
  },
  sleep_end_time: {
    id: "sleep_end_time",
    domain: "sleep",
    label: "Heure de Réveil",
    description: "Heure estimée ou réelle du réveil définitif.",
    unit: "HH:MM",
    allowedUnits: ["HH:MM"],
    sourceTypes: ["garmin", "manual"],
    valueType: "text",
    aggregation: "latest",
    confidenceRules: [],
    scientificStatus: "robust",
    medicalRisk: "none"
  },
  sleep_latency: {
    id: "sleep_latency",
    domain: "sleep",
    label: "Latence d'Endormissement",
    description: "Temps nécessaire pour s'endormir après le coucher.",
    unit: "min",
    allowedUnits: ["min"],
    sourceTypes: ["garmin", "manual"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: false,
    confidenceRules: ["Peut être surestimé si l'utilisateur reste immobile en lisant"],
    scientificStatus: "probable",
    medicalRisk: "none"
  },
  sleep_restlessness: {
    id: "sleep_restlessness",
    domain: "sleep",
    label: "Agitation du Sommeil",
    description: "Indicateur qualitatif de l'agitation ou des mouvements durant la nuit.",
    unit: "/100",
    allowedUnits: ["/100"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: false,
    confidenceRules: [],
    scientificStatus: "exploratory",
    medicalRisk: "none"
  },

  // === Garmin - Activity ===
  activity_duration: {
    id: "activity_duration",
    domain: "training",
    label: "Durée de l'Activité",
    description: "Temps effectif de la séance de sport.",
    unit: "min",
    allowedUnits: ["h", "min", "s"],
    sourceTypes: ["garmin", "manual"],
    valueType: "number",
    aggregation: "sum",
    higherIsBetter: true,
    confidenceRules: [],
    scientificStatus: "robust",
    medicalRisk: "none"
  },
  activity_distance: {
    id: "activity_distance",
    domain: "training",
    label: "Distance de l'Activité",
    description: "Distance parcourue lors de l'activité.",
    unit: "km",
    allowedUnits: ["km", "m"],
    sourceTypes: ["garmin", "manual"],
    valueType: "number",
    aggregation: "sum",
    higherIsBetter: true,
    confidenceRules: ["Basé sur GPS (très robuste) ou accélérométrie intérieure (estimation)"],
    scientificStatus: "robust",
    medicalRisk: "none"
  },
  activity_calories: {
    id: "activity_calories",
    domain: "training",
    label: "Calories d'Activité (Séquence)",
    description: "Calories dépensées spécifiquement durant l'exercice.",
    unit: "kcal",
    allowedUnits: ["kcal", "kJ"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "sum",
    higherIsBetter: true,
    confidenceRules: ["Considéré comme une estimation empirique, jamais comme mesure exacte"],
    scientificStatus: "probable",
    medicalRisk: "none"
  },
  active_calories: {
    id: "active_calories",
    domain: "training",
    label: "Calories Actives Journalières",
    description: "Somme des calories dépensées au-delà du métabolisme de base sur la journée.",
    unit: "kcal",
    allowedUnits: ["kcal", "kJ"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "sum",
    higherIsBetter: true,
    confidenceRules: ["Estimation mathématique sujette à erreur selon l'étalonnage de la fréquence cardiaque"],
    scientificStatus: "probable",
    medicalRisk: "none"
  },
  steps: {
    id: "steps",
    domain: "training",
    label: "Nombre de pas",
    description: "Compteur de pas quotidien.",
    unit: "steps",
    allowedUnits: ["steps"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "sum",
    higherIsBetter: true,
    confidenceRules: [],
    scientificStatus: "robust",
    medicalRisk: "none"
  },
  elevation_gain: {
    id: "elevation_gain",
    domain: "training",
    label: "Dénivelé Positif",
    description: "Cumul de dénivelé positif gravi.",
    unit: "m",
    allowedUnits: ["m"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "sum",
    higherIsBetter: true,
    confidenceRules: [],
    scientificStatus: "robust",
    medicalRisk: "none"
  },
  training_load: {
    id: "training_load",
    domain: "training",
    label: "Charge d'Entraînement Garmin",
    description: "Mesure Garmin de l'impact de l'effort (EPOC cumulé).",
    unit: "points",
    allowedUnits: ["points"],
    sourceTypes: ["garmin", "derived"],
    valueType: "number",
    aggregation: "sum",
    higherIsBetter: true,
    confidenceRules: ["Exige un historique cardiaque étalonné pour être pertinent"],
    scientificStatus: "probable",
    medicalRisk: "none"
  },
  training_effect_aerobic: {
    id: "training_effect_aerobic",
    domain: "training",
    label: "Training Effect Aérobie",
    description: "Bénéfice de la séance pour l'endurance aérobie (0.0 à 5.0).",
    unit: "/5",
    allowedUnits: ["/5"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: true,
    confidenceRules: [],
    scientificStatus: "probable",
    medicalRisk: "none"
  },
  training_effect_anaerobic: {
    id: "training_effect_anaerobic",
    domain: "training",
    label: "Training Effect Anaérobie",
    description: "Bénéfice de la séance pour la vitesse / capacité anaérobie (0.0 à 5.0).",
    unit: "/5",
    allowedUnits: ["/5"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: true,
    confidenceRules: [],
    scientificStatus: "probable",
    medicalRisk: "none"
  },
  lthr: {
    id: "lthr",
    domain: "training",
    label: "Seuil Lactique (FC)",
    description: "Fréquence cardiaque au seuil lactique estimée par Garmin.",
    unit: "bpm",
    allowedUnits: ["bpm"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "latest",
    higherIsBetter: true,
    confidenceRules: ["Dépend de la précision des données d'effort maximal récents"],
    scientificStatus: "probable",
    medicalRisk: "none"
  },
  ftp: {
    id: "ftp",
    domain: "training",
    label: "Puissance au Seuil Fonctionnel (FTP)",
    description: "Estimation de la puissance pouvant être maintenue pendant 1h.",
    unit: "W",
    allowedUnits: ["W"],
    sourceTypes: ["garmin", "manual"],
    valueType: "number",
    aggregation: "latest",
    higherIsBetter: true,
    confidenceRules: ["Dépend de la qualité du capteur de puissance et d'efforts maximaux"],
    scientificStatus: "probable",
    medicalRisk: "none"
  },
  vo2max: {
    id: "vo2max",
    domain: "biometrics",
    label: "VO2 Max",
    description: "Estimation Garmin de la consommation maximale d'oxygène.",
    unit: "ml/kg/min",
    allowedUnits: ["ml/kg/min"],
    sourceTypes: ["garmin", "derived"],
    valueType: "number",
    aggregation: "latest",
    higherIsBetter: true,
    confidenceRules: ["Assez précis en course de fond, moins fiable en terrain vallonné ou hors sports d'endurance"],
    scientificStatus: "probable",
    medicalRisk: "requires_context"
  },
  power_avg: {
    id: "power_avg",
    domain: "training",
    label: "Puissance Moyenne",
    description: "Puissance développée en watts (cyclisme ou course à pied compatible).",
    unit: "W",
    allowedUnits: ["W"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "mean",
    confidenceRules: ["Exige un capteur de puissance étalonné rigoureusement"],
    scientificStatus: "robust",
    medicalRisk: "none"
  },
  power_max: {
    id: "power_max",
    domain: "training",
    label: "Puissance Maximale",
    description: "Puissance maximale instantanée mesurée en watts.",
    unit: "W",
    allowedUnits: ["W"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "max",
    confidenceRules: [],
    scientificStatus: "robust",
    medicalRisk: "none"
  },
  cadence_avg: {
    id: "cadence_avg",
    domain: "training",
    label: "Cadence Moyenne",
    description: "Fréquence moyenne des foulées ou des rotations de pédale.",
    unit: "rpm",
    allowedUnits: ["rpm", "spm"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "mean",
    confidenceRules: [],
    scientificStatus: "robust",
    medicalRisk: "none"
  },
  pace_avg: {
    id: "pace_avg",
    domain: "training",
    label: "Allure Moyenne",
    description: "Temps requis par kilomètre (spécifique course à pied).",
    unit: "min/km",
    allowedUnits: ["min/km"],
    sourceTypes: ["garmin"],
    valueType: "text",
    aggregation: "latest",
    confidenceRules: [],
    scientificStatus: "robust",
    medicalRisk: "none"
  },
  speed_avg: {
    id: "speed_avg",
    domain: "training",
    label: "Vitesse Moyenne",
    description: "Vitesse moyenne globale au cours de la séance.",
    unit: "km/h",
    allowedUnits: ["km/h", "m/s"],
    sourceTypes: ["garmin"],
    valueType: "number",
    aggregation: "mean",
    confidenceRules: [],
    scientificStatus: "robust",
    medicalRisk: "none"
  },
  hr_zone_1_time: { id: "hr_zone_1_time", domain: "training", label: "Temps Zone 1 (Récupération)", description: "Temps passé sous 60% FC Max.", unit: "min", allowedUnits: ["min", "s"], sourceTypes: ["garmin"], valueType: "number", aggregation: "sum", confidenceRules: [], scientificStatus: "probable", medicalRisk: "none" },
  hr_zone_2_time: { id: "hr_zone_2_time", domain: "training", label: "Temps Zone 2 (Aérobie de Base)", description: "Temps passé dans la zone de développement de l'endurance.", unit: "min", allowedUnits: ["min", "s"], sourceTypes: ["garmin"], valueType: "number", aggregation: "sum", confidenceRules: [], scientificStatus: "robust", medicalRisk: "none" },
  hr_zone_3_time: { id: "hr_zone_3_time", domain: "training", label: "Temps Zone 3 (Tempo)", description: "Temps passé dans l'intensité d'endurance active.", unit: "min", allowedUnits: ["min", "s"], sourceTypes: ["garmin"], valueType: "number", aggregation: "sum", confidenceRules: [], scientificStatus: "probable", medicalRisk: "none" },
  hr_zone_4_time: { id: "hr_zone_4_time", domain: "training", label: "Temps Zone 4 (Seuil)", description: "Temps passé proche du seuil anaérobie lactique.", unit: "min", allowedUnits: ["min", "s"], sourceTypes: ["garmin"], valueType: "number", aggregation: "sum", confidenceRules: [], scientificStatus: "robust", medicalRisk: "none" },
  hr_zone_5_time: { id: "hr_zone_5_time", domain: "training", label: "Temps Zone 5 (PMA / Anaérobie)", description: "Temps passé à l'intensité maximale supérieure au seuil.", unit: "min", allowedUnits: ["min", "s"], sourceTypes: ["garmin"], valueType: "number", aggregation: "sum", confidenceRules: [], scientificStatus: "robust", medicalRisk: "none" },

  // === Formulaires Utilisateur - Subjectif ===
  subjective_fatigue: {
    id: "subjective_fatigue",
    domain: "recovery",
    label: "Fatigue Subjective",
    description: "Sensation générale d'épuisement évaluée par l'athlète le matin (1-7).",
    unit: "1-7",
    allowedUnits: ["1-7"],
    sourceTypes: ["manual"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: false,
    confidenceRules: [],
    scientificStatus: "robust",
    medicalRisk: "none"
  },
  subjective_stress: {
    id: "subjective_stress",
    domain: "mental",
    label: "Stress Subjectif",
    description: "Niveau de stress psychologique global perçu par l'utilisateur (1-7).",
    unit: "1-7",
    allowedUnits: ["1-7"],
    sourceTypes: ["manual"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: false,
    confidenceRules: [],
    scientificStatus: "robust",
    medicalRisk: "none"
  },
  subjective_sleep_quality: {
    id: "subjective_sleep_quality",
    domain: "sleep",
    label: "Qualité ressentie du Sommeil",
    description: "Perception subjective de la qualité de la nuit par l'utilisateur (1-7). À distinguer du score Garmin.",
    unit: "1-7",
    allowedUnits: ["1-7"],
    sourceTypes: ["manual"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: true,
    confidenceRules: [],
    scientificStatus: "robust",
    medicalRisk: "none"
  },
  subjective_soreness: {
    id: "subjective_soreness",
    domain: "recovery",
    label: "Courbatures",
    description: "Niveau de sensibilité ou de rigidité musculaire perçu (1-7).",
    unit: "1-7",
    allowedUnits: ["1-7"],
    sourceTypes: ["manual"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: false,
    confidenceRules: [],
    scientificStatus: "robust",
    medicalRisk: "none"
  },
  subjective_mood: {
    id: "subjective_mood",
    domain: "mental",
    label: "Humeur / Moral",
    description: "État de bien-être mental global ressenti (1-7).",
    unit: "1-7",
    allowedUnits: ["1-7"],
    sourceTypes: ["manual"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: true,
    confidenceRules: [],
    scientificStatus: "robust",
    medicalRisk: "none"
  },
  motivation: {
    id: "motivation",
    domain: "mental",
    label: "Motivation",
    description: "Désir ou enthousiasme à s'entraîner ou agir (1-7).",
    unit: "1-7",
    allowedUnits: ["1-7"],
    sourceTypes: ["manual"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: true,
    scientificStatus: "robust",
    medicalRisk: "none",
    confidenceRules: []
  },
  digestive_comfort: {
    id: "digestive_comfort",
    domain: "nutrition",
    label: "Confort Digestif",
    description: "Qualité de la digestion, absence de ballonnements ou de maux d'estomac (1-5).",
    unit: "1-5",
    allowedUnits: ["1-5"],
    sourceTypes: ["manual"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: true,
    scientificStatus: "probable",
    medicalRisk: "requires_context",
    confidenceRules: []
  },
  pain_score: {
    id: "pain_score",
    domain: "recovery",
    label: "Score de Douleur Musculo-Squelettique",
    description: "Score d'intensité de douleur spécifique hors courbatures (0-10, échelle visuelle analogique).",
    unit: "0-10",
    allowedUnits: ["0-10"],
    sourceTypes: ["manual"],
    valueType: "number",
    aggregation: "max",
    higherIsBetter: false,
    scientificStatus: "robust",
    medicalRisk: "medical_boundary",
    confidenceRules: ["Si douleur ≥ 7/10, la readiness est plafonnée de manière protectrice"]
  },
  pain_location: {
    id: "pain_location",
    domain: "recovery",
    label: "Localisation Douleur",
    description: "Zone spécifique de survenue de la douleur.",
    unit: "text",
    allowedUnits: [],
    sourceTypes: ["manual"],
    valueType: "text",
    aggregation: "latest",
    scientificStatus: "robust",
    medicalRisk: "none",
    confidenceRules: []
  },
  illness_symptoms: {
    id: "illness_symptoms",
    domain: "recovery",
    label: "Symptômes / Indisposition",
    description: "Déclaration de présence de symptômes ou d'indisposition physique.",
    unit: "boolean",
    allowedUnits: [],
    sourceTypes: ["manual"],
    valueType: "boolean",
    aggregation: "max",
    higherIsBetter: false,
    scientificStatus: "robust",
    medicalRisk: "medical_boundary",
    confidenceRules: ["Si actif, la readiness est plafonnée d'office"]
  },
  rpe: {
    id: "rpe",
    domain: "training",
    label: "Intensité Perçue (RPE)",
    description: "Rate of Perceived Exertion (0-10 on Borg CR10 modified scale).",
    unit: "0-10",
    allowedUnits: ["0-10"],
    sourceTypes: ["manual"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: false,
    scientificStatus: "robust",
    medicalRisk: "none",
    confidenceRules: []
  },
  session_rpe_load: {
    id: "session_rpe_load",
    domain: "training",
    label: "Charge Subjective Séance (RPE * Durée)",
    description: "Calcul mathématique de la charge interne perçue (RPE x Durée en minutes).",
    unit: "points",
    allowedUnits: ["points"],
    sourceTypes: ["derived"],
    valueType: "number",
    aggregation: "sum",
    higherIsBetter: false,
    scientificStatus: "robust",
    medicalRisk: "none",
    confidenceRules: []
  },
  hydration_volume: {
    id: "hydration_volume",
    domain: "nutrition",
    label: "Hydratation",
    description: "Volume d'eau ou liquide bu au cours de la journée.",
    unit: "ml",
    allowedUnits: ["ml", "L"],
    sourceTypes: ["manual"],
    valueType: "number",
    aggregation: "sum",
    higherIsBetter: true,
    scientificStatus: "robust",
    medicalRisk: "none",
    confidenceRules: []
  },
  urine_color: {
    id: "urine_color",
    domain: "nutrition",
    label: "Couleur des urines (Hydratation)",
    description: "Indicateur visuel d'hydratation (1 = clair, 8 = foncé / déshydraté).",
    unit: "1-8",
    allowedUnits: ["1-8"],
    sourceTypes: ["manual"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: false,
    scientificStatus: "robust",
    medicalRisk: "none",
    confidenceRules: []
  },
  body_weight: {
    id: "body_weight",
    domain: "biometrics",
    label: "Poids Seizure Manuelle",
    description: "Enregistrement direct du poids corporel en kg.",
    unit: "kg",
    allowedUnits: ["kg"],
    sourceTypes: ["manual"],
    valueType: "number",
    aggregation: "latest",
    higherIsBetter: true,
    scientificStatus: "robust",
    medicalRisk: "none",
    confidenceRules: []
  },
  menstrual_flow: {
    id: "menstrual_flow",
    domain: "context",
    label: "Flux Menstruel",
    description: "Niveau de flux menstruel déclaré (aucun, spotting, léger, moyen, abondant).",
    unit: "categorical",
    allowedUnits: [],
    sourceTypes: ["manual"],
    valueType: "categorical",
    aggregation: "latest",
    scientificStatus: "robust",
    medicalRisk: "none",
    confidenceRules: []
  },
  menstrual_pain: {
    id: "menstrual_pain",
    domain: "context",
    label: "Douleur Menstruelle (Dysménorrhée)",
    description: "Intensité des crampes menstruelles (0-10).",
    unit: "0-10",
    allowedUnits: ["0-10"],
    sourceTypes: ["manual"],
    valueType: "number",
    aggregation: "max",
    higherIsBetter: false,
    scientificStatus: "robust",
    medicalRisk: "wellness_only",
    confidenceRules: []
  },
  cycle_symptoms: {
    id: "cycle_symptoms",
    domain: "context",
    label: "Symptômes du Cycle",
    description: "Symptômes syndromiques déclarés (maux de tête, fatigue du cycle, SPM, etc.).",
    unit: "categorical",
    allowedUnits: [],
    sourceTypes: ["manual"],
    valueType: "categorical",
    aggregation: "latest",
    scientificStatus: "probable",
    medicalRisk: "none",
    confidenceRules: []
  },
  energy_level: {
    id: "energy_level",
    domain: "recovery",
    label: "Niveau d'Énergie",
    description: "Énergie physique subjective globale ressentie au coucher ou au lever (1-10).",
    unit: "1-10",
    allowedUnits: ["1-10"],
    sourceTypes: ["manual"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: true,
    scientificStatus: "robust",
    medicalRisk: "none",
    confidenceRules: []
  },
  appetite: {
    id: "appetite",
    domain: "nutrition",
    label: "Appétit",
    description: "Ressenti subjectif de faim globale (1-5 = faible à féroce).",
    unit: "1-5",
    allowedUnits: ["1-5"],
    sourceTypes: ["manual"],
    valueType: "number",
    aggregation: "mean",
    higherIsBetter: true,
    scientificStatus: "probable",
    medicalRisk: "none",
    confidenceRules: []
  },
  notes_context: {
    id: "notes_context",
    domain: "context",
    label: "Notes Contextuelles",
    description: "Texte libre pour décrire des indicateurs externes (voyage, alcool, stress professionnel).",
    unit: "text",
    allowedUnits: [],
    sourceTypes: ["manual"],
    valueType: "text",
    aggregation: "latest",
    scientificStatus: "robust",
    medicalRisk: "none",
    confidenceRules: []
  }
};
